# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-26 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainnav',
            old_name='image',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='mainwheel',
            old_name='image',
            new_name='img',
        ),
    ]
