# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-26 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0002_auto_20180926_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainMustBuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=16)),
                ('trackid', models.IntegerField(default=4)),
            ],
            options={
                'db_table': 'axf_mustbuy',
            },
        ),
    ]
