# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-29 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0008_axfuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='axfuser',
            name='u_icon',
            field=models.ImageField(upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
