# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-07 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import one.models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0011_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_price', models.FloatField(default=0)),
                ('o_time', models.DateTimeField(auto_now=True)),
                ('o_status', models.IntegerField(default=1)),
                ('o_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='one.AXFUser')),
            ],
            options={
                'db_table': 'axf_order',
            },
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_goods', models.FloatField(verbose_name=one.models.Goods)),
                ('o_goods_num', models.IntegerField(default=1)),
                ('o_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='one.Order')),
            ],
            options={
                'db_table': 'axf_ordergoods',
            },
        ),
    ]
