# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-07 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0012_order_ordergoods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergoods',
            name='o_goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='one.Goods'),
        ),
    ]
