# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-11 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESTApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='is_super',
            field=models.BooleanField(default=False),
        ),
    ]
