"""empty message

Revision ID: 966db82ca743
Revises: 
Create Date: 2018-10-19 10:32:25.755405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '966db82ca743'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('g_name', sa.String(length=64), nullable=True),
    sa.Column('g_price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goods')
    # ### end Alembic commands ###
