# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-13 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181012_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_address', models.CharField(max_length=256)),
                ('a_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_list', to='app.UserModel')),
            ],
        ),
    ]
