# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-13 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_addressmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressmodel',
            name='a_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_list', to='app.UserModel'),
        ),
    ]
