"""empty message

Revision ID: ceda533631c5
Revises: 0578af7bf32e
Create Date: 2018-10-18 14:38:33.001529

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ceda533631c5'
down_revision = '0578af7bf32e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('_s_password', sa.String(length=256), nullable=True))
    op.drop_column('student', 's_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('s_password', mysql.VARCHAR(length=256), nullable=True))
    op.drop_column('student', '_s_password')
    # ### end Alembic commands ###
