# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-25 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0002_auto_20180925_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='image',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='movies',
            name='request_url',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='movies',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
