"""empty message

Revision ID: 7fe264f62d45
Revises: 1903ba4679b3
Create Date: 2018-10-17 16:02:44.809437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fe264f62d45'
down_revision = '1903ba4679b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('c_name', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('address',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('a_position', sa.String(length=16), nullable=True),
    sa.Column('a_coutomer', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['a_coutomer'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('address')
    op.drop_table('customer')
    # ### end Alembic commands ###
