"""empty message

Revision ID: 5eaaa7360a6f
Revises: 
Create Date: 2018-10-26 15:38:55.461710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eaaa7360a6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boke_user_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('u_phone', sa.String(length=32), nullable=True),
    sa.Column('u_email', sa.String(length=64), nullable=True),
    sa.Column('_password', sa.String(length=256), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('u_icon', sa.String(length=255), nullable=True),
    sa.Column('is_super', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('u_email'),
    sa.UniqueConstraint('u_phone')
    )
    op.create_table('boke_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('b_user_id', sa.Integer(), nullable=True),
    sa.Column('b_title', sa.String(length=256), nullable=True),
    sa.Column('b_content', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['b_user_id'], ['boke_user_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('boke_model')
    op.drop_table('boke_user_model')
    # ### end Alembic commands ###
