"""empty message

Revision ID: a89fa592522c
Revises: 5eaaa7360a6f
Create Date: 2018-10-26 16:28:51.321014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a89fa592522c'
down_revision = '5eaaa7360a6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_boke_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('b_user_id', sa.Integer(), nullable=True),
    sa.Column('b_boke_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['b_boke_id'], ['boke_model.id'], ),
    sa.ForeignKeyConstraint(['b_user_id'], ['boke_user_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_boke_model')
    # ### end Alembic commands ###
