"""empty message

Revision ID: 8040f4d92d0c
Revises: e0bd4a35dddf
Create Date: 2018-10-17 16:01:01.051744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8040f4d92d0c'
down_revision = 'e0bd4a35dddf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('c_name', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('address',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('a_position', sa.String(length=128), nullable=True),
    sa.Column('a_customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['a_customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('address')
    op.drop_table('customer')
    # ### end Alembic commands ###
